### ISSUE TITLE
0.3.1 vault-secrets-reloader crashing with panic

### ISSUE THREAD

**Issue by gera-corp** [bank-vaults/vault-secrets-reloader#330]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-secrets-reloader/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://bank-vaults.dev/docs/support) without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct).

### Version

0.3.1

### Secrets Webhook Version

1.21.3

### Kubernetes Version

1.31.2

### Kubernetes Distribution/Provisioner

self-hosted

### Expected Behavior

pod vault-secrets-reloader doesn't crash

### Actual Behavior

pod vault-secrets-reloader crashing with panic

### Steps To Reproduce

1. change vault secret version with new secret data
2. waiting for the trigger to restart the pod

### Logs

```shell
time=2024-11-27T12:26:09.423Z level=INFO msg="Setting up event handlers" app=vault-secrets-reloader
time=2024-11-27T12:26:09.423Z level=INFO msg="Starting vault-secrets-reloader controller" app=vault-secrets-reloader
time=2024-11-27T12:26:09.423Z level=INFO msg="Waiting for informer caches to sync" app=vault-secrets-reloader
time=2024-11-27T12:26:09.443Z level=INFO msg="Collected secrets from Deployment tools/vault-test" app=vault-secrets-reloader worker=collector
time=2024-11-27T12:26:09.524Z level=INFO msg="Reloader started" app=vault-secrets-reloader worker=reloader
time=2024-11-27T12:26:09.524Z level=INFO msg="Initializing Vault client" app=vault-secrets-reloader
time=2024-11-27T12:26:09.588Z level=INFO msg="received new Vault token" app=vault-secrets-reloader addr="" role=default path=kubernetes
time=2024-11-27T12:26:09.588Z level=INFO msg="initial Vault token arrived" app=vault-secrets-reloader
time=2024-11-27T12:26:09.600Z level=INFO msg="Vault client initialized" app=vault-secrets-reloader
time=2024-11-27T12:26:09.608Z level=INFO msg="renewed Vault token" app=vault-secrets-reloader ttl=1h0m0s
time=2024-11-27T12:26:09.610Z level=INFO msg="No workloads to reload" app=vault-secrets-reloader worker=reloader
time=2024-11-27T12:27:09.444Z level=INFO msg="Collected secrets from Deployment tools/vault-test" app=vault-secrets-reloader worker=collector
time=2024-11-27T12:28:09.445Z level=INFO msg="Collected secrets from Deployment tools/vault-test" app=vault-secrets-reloader worker=collector
time=2024-11-27T12:28:09.610Z level=INFO msg="Reloader started" app=vault-secrets-reloader worker=reloader
time=2024-11-27T12:28:09.626Z level=INFO msg="Reloading workload: {vault-test tools Deployment}" app=vault-secrets-reloader worker=reloader
panic: sync: negative WaitGroup counter

goroutine 193 [running]:
sync.(*WaitGroup).Add(0x0?, 0x0?)
	/usr/local/go/src/sync/waitgroup.go:64 +0xd8
sync.(*WaitGroup).Done(...)
	/usr/local/go/src/sync/waitgroup.go:89
github.com/bank-vaults/vault-secrets-reloader/pkg/reloader.(*Controller).runReloader.func2({{0xc0005b58b0, 0xa}, {0xc0005b58ba, 0x5}, {0x22fb94c, 0xa}})
	/usr/local/src/vault-secrets-reloader/pkg/reloader/reloader.go:93 +0x257
created by github.com/bank-vaults/vault-secrets-reloader/pkg/reloader.(*Controller).runReloader in goroutine 63
	/usr/local/src/vault-secrets-reloader/pkg/reloader/reloader.go:85 +0x4da
```

### Additional Information

in version v0.3.0 don't have this issue

**Comment by csatib02** [comment]
Hey @gera-corp,
Thanks for raising this!
Would you be able to share some manifests you were using while encountering this, so we can better investigate.

**Comment by gera-corp** [comment]
I use deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-test
  namespace: tools # dont use ns vault and kube-system, details kubectl describe MutatingWebhookConfiguration vault-secrets-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault
      annotations:
        secrets-reloader.security.bank-vaults.io/reload-on-secret-change: "true"
    spec:
      serviceAccountName: default
      containers:
      - name: alpine
        image: alpine
        command: ["sh", "-c", "echo $FOO && echo going to sleep... && sleep 10000"]
        env:
        - name: FOO
          value: vault:secret/data/demosecret/aws#AWS_SECRET_ACCESS_KEY
```
